name: Create Micmute Release ZIP

on:
  push:
    branches:
      - main
    paths:
      - 'micmute/**'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if micmute directory exists
        run: |
          if [ ! -d "micmute" ]; then
            echo "Error: Directory micmute does not exist"
            exit 1
          fi

      - name: Extract version from MicMute.cs
        id: version
        run: |
          VERSION=$(grep 'private const string Version' micmute/MicMute.cs | sed 's/.*Version = "\(.*\)";/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create ZIP archive
        run: |
          zip -r micmute.zip micmute

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: micmute-${{ steps.version.outputs.version }}
          name: MicMute ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          files: micmute.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
